### ISSUE TITLE
Cons of jupyter notebooks

### ISSUE THREAD

**Issue by divyaramamoorthy** [maalcantar/bedl_jupyter_notebook_resources#2]
In README intro:
Do you want to mention the use-cases where you may not want to use a Jupyter notebook - ex: exploratory vs scripted analysis

**Comment by pablocarderam** [comment]
Lol I wrote an unnecessarily more wordy comment to this effect in my feedback too—so agree!

**Comment by jackievaleri** [comment]
MA handled in beb51c1674c04e46852036ac0007ede276fe042b
