### ISSUE TITLE
Clarify Util.py path for import

### ISSUE THREAD

**Issue by divyaramamoorthy** [maalcantar/bedl_jupyter_notebook_resources#5]
Mention that in order to import from utils with ‘from utils import *’, the util.py file needs to be in the same folder as the notebook (at least as its defined now)
- Could add this in the FAQs or as a comment in utils.py file (with examples of how to import if they’re not in the same folder)

**Comment by pablocarderam** [comment]
Very true.

**Comment by jackievaleri** [comment]
Handled in 6f856bf62578fb285ae4ae1c453d15182a2ce6aa
