### ISSUE TITLE
add example of utils auto-reload

### ISSUE THREAD

**Issue by divyaramamoorthy** [maalcantar/bedl_jupyter_notebook_resources#6]
One thing that I found tricky was that to update a utils py, you have to restart the kernel - you could include information about how to use autoreload to help address this
```
%load_ext autoreload
%autoreload 2
```

**Comment by pablocarderam** [comment]
Woah I'm learning tons today

**Comment by jackievaleri** [comment]
I didn't know this!! Addressed in 07aafd67aec7f610b7b2599984b1fc1a3c841d7c.
