### ISSUE TITLE
LaTeX doesn't render if viewing the notebook on GitHub

### ISSUE THREAD

**Issue by pablocarderam** [maalcantar/bedl_jupyter_notebook_resources#8]
In `bedl_jupyter_notebook_resources/Frequently_Asked_Questions_About_Jupyter.ipynb`:
LaTeX doesn't render if viewing the notebook on GitHub.

Maybe add a note saying that in order to view the LaTeX equation (and play around with the rest of the notebook), you should download and run the Jupyter Notebook?

**Comment by jackievaleri** [comment]
Handled in 9c63b39ca97139048e167dadebe806e32070a206
